name: segmentation-transfer
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - pytorch=0.4.1
  - torchvision
  - pip:
    - pyyaml
    - click
    - ipython
    - opencv-python
    - h5py
    - requests
